CREATE TRIGGER [dbo].[DISMINUIR_CANTIDAD_EN_BODEGA] --NOMBRE
ON [dbo].[DF] FOR INSERT AS -- ASIGNAR A LA TABLA
BEGIN

DECLARE @ID_PRODUCTO AS INT --DECLARACION DE VARIABLE
DECLARE @CANTIDAD_VENTA AS INT

SET @CANTIDAD_VENTA = (SELECT Cantidad FROM INSERTED)
SET @ID_PRODUCTO = (SELECT idproducto FROM INSERTED)

UPDATE Producto
SET Cexitencia = Cexitencia - @CANTIDAD_VENTA
WHERE idproducto LIKE @ID_PRODUCTO

END
GO

SELEC * FROM DF
SELECT * FROM Producto
GO 



