---TRIGGER----
USE [Panaderia]
GO
/****** Object:  Trigger [dbo].[DISMINUIR_CANTIDAD_EN_BODEGA]    Script Date: 20/10/2016 02:13:03 ******/


CREATE TRIGGER [dbo].[DISMINUIR_CANTIDAD_EN_BODEGA]
ON [dbo].[DF] FOR INSERT AS
BEGIN

DECLARE @ID_PRODUCTO AS INT
DECLARE @CANTIDAD_VENTA AS INT

SET @CANTIDAD_VENTA = (SELECT cantidad FROM INSERTED)
SET @ID_PRODUCTO = (SELECT idproducto FROM INSERTED)

UPDATE producto
SET CExistencia = CExistencia - @CANTIDAD_VENTA
WHERE idproducto LIKE @ID_PRODUCTO

END

GO

SELECT * FROM DF
SELECT * FROM producto
--SELCET * FORM 